//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCUtility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyStatu
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime ReachingAt { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Lunch { get; set; }
    }
}
