//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCUtility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTable
    {
        public int Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string LeaveType { get; set; }
        public string Reason { get; set; }
        public bool InformedClient { get; set; }
        public Nullable<double> BalanceLeaves { get; set; }
    }
}
